steps:
    ##############################################################################
    #############################    build     ##################################
    ##############################################################################
      ### build server
      - name: 'maven:3-jdk-8'
        entrypoint: 'bash'
        args:
        - '-c'
        - |
          apt-get update && apt-get install -y git r-base r-base-dev libkrb5-dev python-pip python3-pip \
          && git clone https://github.com/apache/incubator-livy && cd incubator-livy \
          && git reset --hard $_LIVY_COMMIT_HASH \
          && pip install cloudpickle==1.3.0 requests==2.23.0 requests-kerberos==0.12.0 flake8==3.7.9 flaky==3.6.1 pytest==4.6.9 configparser==3.5.0 \
          && mvn package


    ##############################################################################
    #############################    deploy     ##################################
    ##############################################################################
      # - name: 'gcr.io/cloud-builders/kubectl'
      #   args:
      #     - 'rollout'
      #     - 'restart'
      #     - 'deployment'
      #     - 'server'
      #   env:
      #     - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
      #     - 'CLOUDSDK_CONTAINER_CLUSTER=cdp-dev-taiwan-k8s'
      #     - 'KUBECTL_VERSION=1.15'

    timeout: 3600s

    options:
      machineType: "N1_HIGHCPU_32"
