steps:
  ##############################################################################
  #############################    build     ##################################
  ##############################################################################
    ### build server
    - name: 'maven:3-jdk-8'
      entrypoint: 'bash'
      args:
      - '-c'
      - |
        cat aaa


  ##############################################################################
  #############################    deploy     ##################################
  ##############################################################################
    # - name: 'gcr.io/cloud-builders/kubectl'
    #   args:
    #     - 'rollout'
    #     - 'restart'
    #     - 'deployment'
    #     - 'server'
    #   env:
    #     - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
    #     - 'CLOUDSDK_CONTAINER_CLUSTER=cdp-dev-taiwan-k8s'
    #     - 'KUBECTL_VERSION=1.15'

timeout: 3600s

options:
  machineType: "N1_HIGHCPU_32"
